permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: littleroach110
  email: littleroach110@gmail.com
  #link: http://painterlin.com
  #weibo: http://weibo.com/orangeissweet
  github: http://github.com/littleroach110
  #music: http://site.douban.com/linanya
  #linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 记录小强思考的地方
description: 网络空间安全，人工智能，人生杂烩
url: http://littleroach110.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/littleroach.png
favicon: /public/img/littleroach-min.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: littleroach110.net

# disqus 设置
#disqus:
#  shortname: painterlin

# 主题设置，自动激活某个标签
active: 资讯

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

# CDN加速网站路径
CDN_PATH: http://ol8zepzvp.bkt.clouddn.com